import Head from 'next/head'

type HeaderProps = {
  title?: string
}

export const Header = ({ title = 'Space X Missions' }: HeaderProps) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)
